-- Q1. What is the total revenue generated by male vs. female customers?


SELECT
gender,
SUM(purchase_amount) as Revenue

FROM customer
GROUP BY gender

 -- Q2. Which customers used a discount but still spent more than the average purchase amount?
 
 SELECT 
 customer_id,purchase_amount
 FROM customer
 WHERE discount_applied = 'Yes' AND
purchase_amount > = (
select 
avg(purchase_amount) 
FROM customer 
)

 -- Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP (5) item_purchased,
       ROUND(AVG(CAST(review_rating AS numeric)) ,3) AS AvgRating
FROM dbo.customer
GROUP BY item_purchased
ORDER BY AvgRating DESC;
 -- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
 -- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
 -- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
 
 SELECT TOP (5)
    item_purchased,
    COUNT(*) AS total_purchases,
    ROUND(
        (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0) / COUNT(*),
        2
    ) AS discount_percentage
FROM dbo.customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC;
 -- Q7. Segment customers into New, Returning, and Loyal based on their 
 --total number of previous purchases, and show the count of each segment.

    with customer_type as (
    SELECT customer_id,previous_purchases,
    CASE 
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
        END AS customer_segment
    FROM customer
    )  
    SELECT customer_segment ,COUNT(*) AS 'Number Of Customers'
    FROM customer_type
    GROUP BY customer_segment
    ORDER BY [Number Of Customers] DESC

 -- Q8. What are the top 3 most purchased products within each category?

with items_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc ) as item_rank
from customer
group by category,item_purchased
)
select
item_rank,category,item_purchased,total_orders
from items_counts
where item_rank <= 3

 -- Q9. Are customers who are repeat buyers 
 --(more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status
 -- Q10. What is the revenue contribution of each age group? 
 select age_group,
 sum(purchase_amount) as total_revenue
 from customer
 group by age_group
 order by total_revenue desc